### ISSUE TITLE
1+1=3?

### ISSUE THREAD

**Issue by richmans** [bradsprojects/Digirule2U#1]
This thing is really fun to play with! (which is definitely not the issue)

I wanted to implement a dice-simulation program. It generates a random number 0-255 which i then try to reduce to a number 1-6.

So i have the following program:
```
  00 SPEED   40
  02 RANDA
  03 COPYAR  E0
  05 COPYLR  2A E1
  08 DIV     E0 E1
  0B COPYRA  E0
  0D SUBLA   06
  0F BTSTSC  00 FC
  12 JUMP    00
  14 COPYRA  E0
  16 ADDLA   01
  18 COPYAR  FF
  1A BTSTSC  07 FD
  1D JUMP    00
  1F JUMP    1A
```

Now if i run this, the `ADDLA 1` at 16 seems to somehow add 2 to the A register instead of 1. So i put a breakpoint on 16, and then stepped through it:

```
> Edit Breakpoint | BP=16 | Address (FF=disable) ? 16
> Go Break
PC=16 | SR=02 .C. | AC=04 | SP=00 | @PC=ADDLA   01
> Display Registers
PC=16 | SR=02 .C. | AC=04 | SP=00 | @PC=ADDLA   01
> Step
PC=18 | SR=00 ... | AC=06 | SP=00 | @PC=COPYAR  FF
>
```

I've done multiple tests, no matter what the AC contains, it always adds 2.

I'm thinking the ADDLA is not functioning in this case?  I tested `COPYLA 1, ADDLA 1`, that works properly. Is there some flag that influences this? Or the RANDA instruction? 

Curious to hear what you think!

Richard

**Comment by photonverse** [comment]
Hi Richard,

I see that Carry bit was set:

> Display Registers
PC=16 | SR=02 .C. | AC=04 | SP=00 | @PC=ADDLA   01

Try "BSET 1 FC" to clear the carry bit before ADDLA instruction.

Kwang

**Comment by bradsprojects** [comment]
Hi Richard,

This is normal behaviour for the DR2U. When stepping through your program you can see the carry flag is set within the Status Register (SR=02) prior to the ADDLA instruction being executed.

If you have a look in the Digirule 2U User Manual, you will find the ADDLA instruction will add a literal value to the accumulator and the carry flag also.

To get your program to work correctly, you simply need to clear the carry flag prior to the ADDLA instruction like this:

```
  00 SPEED   40
  02 RANDA
  03 COPYAR  E0
  05 COPYLR  2A E1
  08 DIV     E0 E1
  0B COPYRA  E0
  0D SUBLA   06
  0F BTSTSC  00 FC
  12 JUMP    00
  14 COPYRA  E0
  16 BCLR    01 FC
  19 ADDLA   01
  1B COPYAR  FF
  1D BTSTSC  07 FD
  20 JUMP    00
  22 JUMP    1A
```

**Comment by photonverse** [comment]
Oops. I meant to say "BCLR 1 FC" (clear carrybit for STATUS REGISTER).

**Comment by bradsprojects** [comment]
Oh, I see you beat me to it @photonverse :)

**Comment by richmans** [comment]
I see! Thanks! I wrote quite a bit of x86 assembly and never saw this behavior in an add instruction so i didn't expect it. Wouldn't it be more intuitive to ignore the carry flag? The incr instruction doesn't use it. 

Anyway, should be able to get this working now, thanks! And thanks for building this great toy! :-)

**Comment by kd0gls** [comment]
Including the carry bit in the ADDxx/SUBxx instructions supports the addition/subtraction of multi-byte numbers.  The 24-bit counter sample program provides an example of this.  The x86 equivalent would be ADC/SBB.
