### ISSUE TITLE
Please specify serial port flow control in the manual

### ISSUE THREAD

**Issue by rlcarr** [bradsprojects/Digirule2U#2]
Could you update the User Manual to specify which flow control scheme should be used when connecting a serial terminal?  Should it be XON/XOFF?  CTS/RTS?  None? Something else?

**Comment by kd0gls** [comment]
Hi rlcarr,

The flow control setting which is often present in communications software is just one of many possible serial device settings you may need to configure, and we don't presume how they should all be set.  We provide only the most essential settings in the user manual.  The Digirule 2U does not support any form of flow control, and you will likely have no trouble communicating with the device regardless of which flow control option you choose, however I would recommend "none".
