### ISSUE TITLE
Cannot update firmware

### ISSUE THREAD

**Issue by flodi** [bradsprojects/Digirule2U#4]
This is the output:
Digirule 2U Firmware Updater | 18 Dec 2020 | KD0GLS
Loading hex file... OK
Opening port... OK
Erasing flash... FAILED! (read error)

I'm on Mac OS 12 lates updates.

**Comment by kd0gls** [comment]
Hi flodi,
Are you following the steps outlined in the Digirule 2U User Manual for updating the firmware?
For your information, your Digirule 2U came with the latest firmware already pre-installed.

**Comment by flodi** [comment]
Yes, I followed the manual. Of course, having the latest firmware, it is not an urgent matter, but it is strange (updating firmware is a test that I always do with every new "toy"...).
  
​
  
​BTW, it is wonderful, I'm the envy on my friends :-)
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  

  
  

Fabrizio Lodi
  CEO

  

flodi@e-scientia.eu
 +39335345390

**Comment by kd0gls** [comment]
I understand completely the desire to try out each and every function of a new toy!  Let me ask a few troubleshooting questions then.

Have you already established that you can successfully communicate with the Digirule 2U through means other than the firmware updater?  For example, the built-in debug monitor and your favorite terminal emulation software is a good means of doing that.

You are following the procedure in the Digirule 2U User Manual section titled "Updating the Firmware", correct?

Are the Run and Stop LEDs on the Digirule 2U alternately blinking prior to you running the udr2 utility?

Have you joined our Discord server?  I think you might find it easier to carry on a conversation there than through GitHub.

(For your information there is a "--verify" option to "udr2" which will allow you to exercise most of the updater feature but without going so far as to actually erase and rewrite the pre-installed firmware.)

**Comment by flodi** [comment]
I followed the firmware update manual, and I was able (I think) to send an hex program.
  
​
  
​The Run and Stop LEDs weren't blinking, I didn't see a step about that in the manual. But that made me think: I forgot something.
  
​
  
​So I went to read again the back of the digirule and, gotcha, that was the bit I forgot. Now it works.
  
​
  
​Thank you again
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  

  
  

Fabrizio Lodi
  CEO

  

flodi@e-scientia.eu
 +39335345390

**Comment by kd0gls** [comment]
You said "The Run and Stop LEDs weren't blinking, I didn't see a step about that in the manual."

The information you're missing is in the main Digirule 2U User Manual, in the section "Updating the Firmware", and is important and worth reading.  The supplemental UDR2 User Manual covers only those details that were too intricate to be included in the main manual, such as the exact syntax for using it under different operating systems.

Glad you have it working now.
